Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = []

src += ['drv_common.c']

path =  [cwd]
path += [cwd + '/config']

if not GetDepend('PKG_CMSIS_CORE'):
    path += [cwd + '/CMSIS/Include']

if GetDepend('BSP_USING_ON_CHIP_FLASH'):
    path += [cwd + '/drv_flash']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
