from building import *
import os

cwd     = GetCurrentDir()
path = [cwd]
src  = []

if GetDepend(['BSP_USING_CAN']):
    src += [cwd + '/can/drv_can.c']
    path += [cwd + '/can']

if GetDepend(['BSP_USING_DWT']):
    src += [cwd + '/dwt/drv_dwt.c']
    path += [cwd + '/dwt']

group = DefineGroup('RM_Drivers', src, depend = [''], CPPPATH = path)

Return('group')
